/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
	id("java")
	application
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jfree:jfreechart:1.5.3")
}

application {
    mainClass.set("module2.week5.task1.a.Permutations") 
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "module2.week5.task1.a.Permutations"
    }
}
